// Retirado do site https://cepbrasil.org/distrito-federal/brasilia/

// Dados coletados usando o seguinte código no console do navegador:

// const bairros = [...document.querySelectorAll(".title")].map((bairro) => {
//   return bairro.innerText;
// })

// const filteredBairros = new Set([...bairros]);
// console.log([...filteredBairros]);

export const allNeighborhoods = [
  "Alto da Boa Vista (Sobradinho)",
  "Arapoanga (Planaltina)",
  "Área Alfa (Santa Maria)",
  "Área de Desenvolvimento Econômico (Águas Claras)",
  "Área de Desenvolvimento Econômico (Ceilândia)",
  "Área de Desenvolvimento Econômico (Núcleo Bandeirante)",
  "Área Octogonal",
  "Área Rural da Vila Estrutural",
  "Área Rural de Brazlândia",
  "Área Rural de Ceilândia",
  "Área Rural de Planaltina",
  "Área Rural de Samambaia",
  "Área Rural de Santa Maria",
  "Área Rural de São Sebastião",
  "Área Rural de Sobradinho",
  "Área Rural de Taguatinga",
  "Área Rural do Gama",
  "Área Rural do Lago Norte",
  "Área Rural do Paranoá",
  "Área Rural do Recanto das Emas",
  "Área Universitária (Planaltina)",
  "Areal (Águas Claras)",
  "Asa Norte",
  "Asa Sul",
  "Bela Vista (São Sebastião)",
  "Bonsucesso (São Sebastião)",
  "Bora Manso",
  "Brazlândia",
  "Campus Universitário",
  "Campus Universitário Darcy Ribeiro",
  "Candangolândia",
  "Ceilândia Centro (Ceilândia)",
  "Ceilândia Norte (Ceilândia)",
  "Ceilândia Sul (Ceilândia)",
  "Centro (São Sebastião)",
  "Cidade Nova (Gama)",
  "Condomínio Chácaras Ana Maria (Santa Maria)",
  "Condomínio Comercial e Residencial Sobradinho (Sobradinho)",
  "Condomínio Coohaplan - Itiquira (Planaltina)",
  "Condomínio Guirra (Planaltina)",
  "Condomínio Império dos Nobres (Sobradinho)",
  "Condomínio Mansões Sobradinho (Sobradinho)",
  "Condomínio Mestre DArmas (Planaltina)",
  "Condomínio Mirante da Serra (Sobradinho)",
  "Condomínio Nosso Lar (Planaltina)",
  "Condomínio Nova Esperança (Planaltina)",
  "Condomínio Parque Mônaco (Planaltina)",
  "Condomínio Parque Mônaco II (Planaltina)",
  "Condomínio Prado (Planaltina)",
  "Condomínio Privê Lucena Roriz (Ceilândia)",
  "Condomínio Residencial Morada Nobre (Planaltina)",
  "Condomínio Residencial Santa Maria (Santa Maria)",
  "Condomínio Residencial Santa Mônica (Santa Maria)",
  "Condomínio Santa Mônica (Planaltina)",
  "Condomínio Vale dos Pinheiros (Sobradinho)",
  "Cruzeiro Novo",
  "Cruzeiro Velho",
  "Del Lago I (Itapoã)",
  "Del Lago II (Itapoã)",
  "Engenho das Lages (Gama)",
  "Estância Mestre DArmas I (Planaltina)",
  "Estância Mestre DArmas II (Planaltina)",
  "Estância Mestre DArmas III (Planaltina)",
  "Estância Mestre DArmas IV (Planaltina)",
  "Estância Mestre DArmas V (Planaltina)",
  "Estância Mestre DArmas VI (Planaltina)",
  "Estância Planaltina (Planaltina)",
  "Estâncias Vila Rica (Sobradinho)",
  "Fazenda Mestre DArmas (Etapa I - Planaltina)",
  "Fazenda Mestre DArmas (Etapa II - Planaltina)",
  "Fazenda Mestre DArmas (Etapa III - Planaltina)",
  "Fazendinha (Itapoã)",
  "Gama",
  "Grande Colorado (Sobradinho)",
  "Granja do Torto",
  "Guará I",
  "Guará II",
  "Incra 8 (Brazlândia)",
  "Itapoã I",
  "Itapoã II",
  "Jardim Roriz (Planaltina)",
  "Jardins Mangueiral (São Sebastião)",
  "João Cândido (São Sebastião)",
  "Mansões Abraão I (Santa Maria)",
  "Mansões Abraão II (Santa Maria)",
  "Mansões do Amanhecer (Planaltina)",
  "Metropolitana (Núcleo Bandeirante)",
  "Morro Azul (São Sebastião)",
  "Norte (Águas Claras)",
  "Nossa Senhora de Fátima (Planaltina)",
  "Nova Colina (Sobradinho)",
  "Núcleo Bandeirante",
  "Núcleo Rural Alagados (Santa Maria)",
  "Núcleo Rural Hortigranjeiro de Santa Maria",
  "Núcleo Rural Lago Oeste (Sobradinho)",
  "Núcleo Rural Santa Maria",
  "Núcleo Rural Vargem Bonita (Núcleo Bandeirante)",
  "Paranoá",
  "Paranoá Parque (Paranoá)",
  "Park Way",
  "Planaltina",
  "Ponte Alta Norte (Gama)",
  "Portal do Amanhecer (Planaltina)",
  "Portal do Amanhecer I (Planaltina)",
  "Portal do Amanhecer III (Planaltina)",
  "Portal do Amanhecer V (Planaltina)",
  "Portal do Amanhecer V (Privê - Planaltina)",
  "Quadras Econômicas Lúcio Costa (Guará)",
  "Quinta dos Ipês (São Sebastião)",
  "Quintas do Amanhecer II (Planaltina)",
  "Quintas do Amanhecer III (Planaltina)",
  "Recanto das Emas",
  "Recanto do Sossego (Planaltina)",
  "Recanto Feliz (Planaltina)",
  "Região dos Lagos (Sobradinho)",
  "Residencial Bica do DER (Gleba B - Planaltina)",
  "Residencial Cachoeira (Planaltina)",
  "Residencial Condomínio Marissol (Planaltina)",
  "Residencial do Bosque (São Sebastião)",
  "Residencial Flamboyant (Planaltina)",
  "Residencial Itaipu (São Sebastião)",
  "Residencial Morro da Cruz (São Sebastião)",
  "Residencial Nova Esperança (Planaltina)",
  "Residencial Nova Planaltina (Planaltina)",
  "Residencial Samauma (Planaltina)",
  "Residencial Sandray (Planaltina)",
  "Residencial Santos Dumont (Santa Maria)",
  "Residencial São Francisco I (Planaltina)",
  "Residencial São Francisco II (Planaltina)",
  "Residencial Sarandy (Planaltina)",
  "Residencial Vitória (São Sebastião)",
  "Riacho Fundo I",
  "Riacho Fundo II",
  "Samambaia Norte (Samambaia)",
  "Samambaia Sul (Samambaia)",
  "San Sebastian (Planaltina)",
  "Santa Maria",
  "São Bartolomeu (São Sebastião)",
  "São Francisco (São Sebastião)",
  "São Gabriel (São Sebastião)",
  "Serra Azul (Sobradinho)",
  "Setor Administrativo (Planaltina)",
  "Setor Central (Gama)",
  "Setor Central (Vila Estrutural)",
  "Setor Comercial Central (Planaltina)",
  "Setor de Áreas Isoladas Sul (Núcleo Bandeirante)",
  "Setor de Chácaras Córrego da Onça (Núcleo Bandeirante)",
  "Setor de Desenvolvimento Econômico (Taguatinga)",
  "Setor de Educação (Planaltina)",
  "Setor de Grandes Áreas Norte (Leste)",
  "Setor de Habitações Individuais Norte",
  "Setor de Habitações Individuais Sul",
  "Setor de Hotéis e Diversões (Planaltina)",
  "Setor de Indústrias Bernardo Sayão (Núcleo Bandeirante)",
  "Setor de Mansões de Sobradinho",
  "Setor de Mansões do Lago Norte",
  "Setor de Mansões Dom Bosco (Lago Sul)",
  "Setor de Mansões Mestre DArmas (Planaltina)",
  "Setor de Materiais de Construção (Ceilândia)",
  "Setor de Postos e Motéis Norte (Lago Norte)",
  "Setor de Postos e Motéis Sul (Núcleo Bandeirante)",
  "Setor Econômico de Sobradinho (Sobradinho)",
  "Setor Especial (Vila Estrutural)",
  "Setor Habitacional Arniqueira (Águas Claras)",
  "Setor Habitacional Contagem (Sobradinho)",
  "Setor Habitacional Fercal (Sobradinho)",
  "Setor Habitacional Jardim Botânico",
  "Setor Habitacional Pôr do Sol (Ceilândia)",
  "Setor Habitacional Ribeirão (Santa Maria)",
  "Setor Habitacional Samambaia (Vicente Pires)",
  "Setor Habitacional Sol Nascente (Ceilândia)",
  "Setor Habitacional Taquari (Lago Norte)",
  "Setor Habitacional Tororó (Santa Maria)",
  "Setor Habitacional Vereda Grande (Taguatinga)",
  "Setor Habitacional Vicente Pires",
  "Setor Hospitalar (Planaltina)",
  "Setor Industrial (Ceilândia)",
  "Setor Industrial (Gama)",
  "Setor Industrial (Sobradinho)",
  "Setor Industrial (Taguatinga)",
  "Setor Juscelino Kubitschek (Núcleo Bandeirante)",
  "Setor Leste (Gama)",
  "Setor Leste (Vila Estrutural)",
  "Setor Mansões Itiquira (Planaltina)",
  "Setor Meireles (Santa Maria)",
  "Setor Militar Urbano",
  "Setor Noroeste",
  "Setor Norte (Brazlândia)",
  "Setor Norte (Gama)",
  "Setor Norte (Planaltina)",
  "Setor Norte (Vila Estrutural)",
  "Setor Oeste (Gama)",
  "Setor Oeste (Sobradinho II)",
  "Setor Oeste (Vila Estrutural)",
  "Setor Placa da Mercedes (Núcleo Bandeirante)",
  "Setor Policial Sul",
  "Setor Recreativo e Cultural (Planaltina)",
  "Setor Residencial Leste (Planaltina)",
  "Setor Residencial Mestre DArmas (Planaltina)",
  "Setor Residencial Norte (Planaltina)",
  "Setor Residencial Oeste (Planaltina)",
  "Setor Residencial Oeste (São Sebastião)",
  "Setor Sudoeste",
  "Setor Sul (Brazlândia)",
  "Setor Sul (Gama)",
  "Setor Sul (Planaltina)",
  "Setor Tradicional",
  "Setor Tradicional (Brazlândia)",
  "Setor Tradicional (Planaltina)",
  "Setor Tradicional (São Sebastião)",
  "Setores Complementares",
  "Sobradinho",
  "Sul (Águas Claras)",
  "Taguatinga Centro (Taguatinga)",
  "Taguatinga Norte",
  "Taguatinga Norte (Taguatinga)",
  "Taguatinga Sul (Taguatinga)",
  "Taquara (Planaltina)",
  "Vale das Acácias (Sobradinho)",
  "Vale do Amanhecer (Planaltina)",
  "Vale do Sol (Planaltina)",
  "Varjão",
  "Veneza I (Planaltina)",
  "Veneza II (Planaltina)",
  "Veneza III (Planaltina)",
  "Veredas (Brazlândia)",
  "Vila Cauhy (Núcleo Bandeirante)",
  "Vila da Telebrasília",
  "Vila Dimas (Planaltina)",
  "Vila do Boa (São Sebastião)",
  "Vila Estrutural",
  "Vila Feliz (Planaltina)",
  "Vila Nossa Senhora de Fátima (Planaltina)",
  "Vila Nova (São Sebastião)",
  "Vila Planalto",
  "Vila Rabelo I (Sobradinho)",
  "Vila Rabelo II (Sobradinho)",
  "Vila São José (Brazlândia)",
  "Vila São José (São Sebastião)",
  "Vila São José (Vicente Pires)",
  "Vila Vicentina (Planaltina)",
  "Zona Cívico-Administrativa",
  "Zona de Dinamização (Santa Maria)",
  "Zona Industrial",
  "Zona Industrial (Guará)"
]
