version: '3.7'

services:
  database_mds:
    image: postgres
    container_name: database_mds
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker_mds
      - POSTGRES_DB=mds
    volumes:
      - pgdata:/data/postgres
    network_mode: host
  app:
    build: .
    container_name: mds
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    network_mode: host

volumes:
  pgdata:
    driver: local
