name: CI

on:
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    defaults:
      run:
        working-directory: server    
        
        
    runs-on: ubuntu-latest

    steps:
    
      - run: pwd
    
      - name: Checkout
        uses: actions/checkout@v2

      - run: pwd

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: "yarn"

      - name: Install dependencies
        run: yarn

      - name: linting
        run: yarn lint

      - name: Run test
        run: npm test

      - name: Vitest Coverage Report
        uses: davelosert/vitest-coverage-report-action@v1.3.1
